using System;
using System.Windows.Forms;

namespace Screentime
{
    public partial class Form1 : Form
    {
        //Object Declarations 
        private Timer timer; //implemented in the system.windows.forms library
        private ApplicationUsageTracker usageTracker; //Custom class implemented in ApplicationUsageTracker.cs
        private ListViewUpdater listViewUpdater; //Custom class implemented in ListViewUpdater.cs

        //Constructor
        public Form1()
        {
            InitializeComponent(); //Auto-generated by Winform Designer. Initializes all components and controls on the form as defined in the designer file
            SetLabelText();
            usageTracker = new ApplicationUsageTracker(); //Creates new instance of the class and assigns it to previously declared object of same class type
            listViewUpdater = new ListViewUpdater(AppUsageListviewControl); //Same function as above - Additionally, passes 'ListView' control to the class constructor (as defined in ListViewUpdater.cs)
            InitializeTimer(); //Initialize timer 
        }

        //Function to initialize timer
        private void InitializeTimer()
        {
            timer = new Timer();
            timer.Interval = 1000; //Sets tick event to occur every interval of: 1 second
            timer.Tick += Timer_Tick; //Subscribes Timer_Tick method to the Tick event of the Timer object. Everytime Tick event occurs, the Timer_Tick method will be called automatically
            timer.Start();
        }

        //Function to trigger additional events every Tick event
        private void Timer_Tick(object sender, EventArgs e)
        {
            usageTracker.UpdateUsageTimes(); 
            listViewUpdater.UpdateListView(usageTracker.GetUsageTimes()); //Calls UpdateListView function and passes the Dictionary 'appUsageTimes' by way of GetUsageTimes function call
        }

        //Function to set/modify the text of all labels placed within Form1
        private void SetLabelText()
        {
            AppUsageDescriptionLabel.Text = "The Application Usage Tracker is a tool designed to monitor and display the amount of time you spend on different applications while your computer is running.\n\nThe AppUsage table below consists of two columns: \"Application Name\" and \"Usage Time\". Each row in the table represents a different application that has been active on your computer.";
        }
    }
}
